/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('@arco-design/web-vue')['Col']
    ARow: typeof import('@arco-design/web-vue')['Row']
    BlurBackgroundColor: typeof import('./src/components/BlurBackgroundColor.vue')['default']
    DefineGuide: typeof import('./src/components/DefineGuide.vue')['default']
    DragBox: typeof import('./src/components/DragBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapChart: typeof import('./src/components/charts/MapChart.vue')['default']
    Menu: typeof import('./src/components/leftMenu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
